"""initial tables

Revision ID: 170ad42e94eb
Revises: 
Create Date: 2018-05-19 12:52:37.422156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '170ad42e94eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('leader_id', mysql.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('leader_id', mysql.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('resource_id', mysql.BIGINT(), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    op.drop_table('permission')
    op.drop_table('employee')
    op.drop_table('department')
    # ### end Alembic commands ###
